[package]
name = "sylt-compiler"
version = "0.2.0"
edition = "2018"

[lib]
path = "src/compiler.rs"

[dependencies]
sylt-common = { version = "0.2.0", path = "../sylt-common" }
sylt-parser = { version = "0.2.0", path = "../sylt-parser" }
