[package]
name = "tihdy"
version = "0.1.0"
authors = ["Edvard Thörnros <edvard.thornros@gmail.com>"]
edition = "2018"

[lib]
name = "tihdy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.11.4"
owo-colors = { git="https://github.com/FredTheDino/owo-colors.git" }
tihdy_derive = { path = "tihdy_derive" }

criterion = { version = "0.3", optional = true }

[profile.release]
debug = true
lto = "thin"

[[bench]]
name = "tihdy_benchmark"
harness = false
