[workspace]

members = [
    "sylt-old",

    "sylt-common",
    "sylt-compiler",
    "sylt-parser",
    "sylt-tokenizer",
    "sylt-typechecker",
    "sylt-machine"
]

[profile.release]
lto = "thin"
