[package]
name = "sylt-parser"
version = "0.2.0"
edition = "2018"

[lib]
path = "src/parser.rs"

[dependencies]
sylt-common = { version = "0.2.0", path = "../sylt-common" }
sylt-tokenizer = { version = "0.2.0", path = "../sylt-tokenizer" }
sylt-macro = { version = "0.2.0", path = "../sylt-macro" }
