[package]
name = "sylt-typechecker"
version = "0.2.0"
edition = "2018"

[lib]
path = "src/typechecker.rs"

[dependencies]
sylt-common = { version = "0.2.0", path = "../sylt-common" }

owo-colors = { git = "https://github.com/FredTheDino/owo-colors.git" }
