[package]
name = "sylt-common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sylt-tokenizer = { path = "../sylt-tokenizer" }

owo-colors = { git = "https://github.com/FredTheDino/owo-colors.git" }
