name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SDL and Lua
      run: sudo apt update && sudo apt install -y libsdl2-dev lua5.3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
