name: Warnings

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Warnings
      run: cargo check --package sylt --no-default-features
